#!/bin/bash

function asciihalfnote {
  echo "        |~~~~~~~~~|"
  echo "        |~~~~~~~~~|"
  echo "        |         |"
  echo "    /~~\|     /~~\|"
  echo "    \__/      \__/"
}

function asciinote {
  echo "               __________"
  echo "              |==========|"
  echo "              |          |"
  echo "              |          |"
  echo "         ____ |     ____ |"
  echo "        /    \|    /    \|"
  echo "       |      |   |      |"
  echo "        \____/     \____/"
}

function guitar {
  echo "                   _,., "
  echo "                 ,'   ,'"
  echo "                /   ,'"
  echo "               /   , "
  echo "              /   ,"
  echo "             /   '"
  echo "            /   ,'"
  echo "            '.__|"
  echo "             |  |"
  echo "             |__|"
  echo "             |  |"
  echo "             |__|"
  echo "             |  |"
  echo "             |__|"
  echo "             |  |"
  echo "             |__|"
  echo "             |, |"
  echo "             |--|"
  echo "             |__|"
  echo "             |  |"
  echo "             |--|"
  echo "             |__|"
  echo "             |__|        ,-."
  echo "             |__|'     ,'  /"
  echo "        _,.-'     ',_,' o /"
  echo "       /     8888        /"
  echo "       |                /"
  echo "        1              /"
  echo "         L   8888     /"
  echo "         |           /"
  echo "        /    ====    \\"
  echo "       /     ____     \\"
  echo "      /     (____)  o  \\"
  echo "     /             o    \\"
  echo "    /             o     ,'"
  echo "   /               _,.'^"
  echo "  /        __,.--~^"
  echo "  \,,..--~~^"
}
